# Generated by Django 2.2.12 on 2020-08-03 17:46

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ops_scpages', '0022_auto_20200803_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('domain', models.CharField(max_length=255, null=True)),
                ('token', models.CharField(help_text='Warning! Changing the token affects the connection to all endpoints.', max_length=255, null=True)),
                ('privilegies_mode', models.CharField(choices=[('polp', 'Principle of least privilege'), ('idc', 'Open privilege')], default='isolate', max_length=255)),
                ('share_mode', models.CharField(choices=[('isolate', 'Prohibit external authentication - Prohibit company page publishing'), ('medium', 'Prohibit external authentication - Allow company page publishing'), ('open', 'Allow external authentication - Allow company page publishing')], default='isolate', max_length=255)),
                ('share_projects', models.BooleanField(default=True)),
                ('share_users', models.BooleanField(default=True)),
                ('share_company_name', models.BooleanField(default=True)),
                ('share_company_recruiting', models.BooleanField(default=True)),
                ('share_company_recruement_url', models.BooleanField(default=True)),
                ('share_company_description', models.BooleanField(default=True)),
                ('share_company_emplyees_count', models.BooleanField(default=True)),
                ('share_company_vat', models.BooleanField(default=True)),
                ('share_company_email', models.BooleanField(default=True)),
                ('share_company_opensource_status', models.BooleanField(default=True)),
                ('share_company_opensource_url', models.BooleanField(default=True)),
                ('company_page', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conntector_scp_page', to='ops_scpages.OpsScpagesPage')),
            ],
        ),
    ]
