# Generated by Django 2.2.12 on 2020-08-03 20:22

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ops_connectors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='company_page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conntector_scp_page', to='ops_scpages.OpsScpagesPage'),
        ),
        migrations.AlterField(
            model_name='connector',
            name='token',
            field=models.CharField(blank=True, help_text='Warning! Changing the token affects the connection to all endpoints.', max_length=255, null=True),
        ),
    ]
