# Generated by Django 2.2.12 on 2020-08-04 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops_connectors', '0003_connectorformfield_connectorformpage_connectorformsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='company_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conntector_scp_page', to='ops_scpages.OpsScpagePage'),
        ),
    ]
