# Generated by Django 2.2.12 on 2020-08-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_connectors', '0004_auto_20200804_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='connector',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
