# Generated by Django 2.2.12 on 2020-08-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_connectors', '0005_auto_20200804_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
