# Generated by Django 2.2.12 on 2020-08-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_connectors', '0006_connector_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
