# Generated by Django 2.2.12 on 2020-08-07 23:05

from django.db import migrations, models
import django.db.models.deletion
import esite.colorfield.blocks
import esite.ops.ops_scpages.models
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('ops_scpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insertions', models.CharField(max_length=255, null=True)),
                ('deletions', models.CharField(max_length=255, null=True)),
                ('path', models.CharField(max_length=255, null=True)),
                ('raw_changes', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpsScpagePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('overview_tab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('feed_section', wagtail.core.fields.StreamField([('feed', wagtail.core.blocks.StructBlock([('data', wagtail.core.blocks.StreamBlock([('commit', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('datetime', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True)), ('issue', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('datetime', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True)), ('pr', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('datetime', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True)), ('review', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('datetime', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=False, icon='fa-newspaper-o', null=True))], blank=True, null=True)),
                ('history_section', wagtail.core.fields.StreamField([('history', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('datetime', wagtail.core.blocks.DateTimeBlock())], blank=False, icon='fa-newspaper-o', null=True))], blank=True, null=True)),
                ('languages_section', wagtail.core.fields.StreamField([('language', wagtail.core.blocks.StructBlock([('language_name', wagtail.core.blocks.CharBlock()), ('color', esite.colorfield.blocks.ColorBlock()), ('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True)),
                ('users_tab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('users_section', wagtail.core.fields.StreamField([('S_UserBlock', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('username', wagtail.core.blocks.CharBlock()), ('active', wagtail.core.blocks.BooleanBlock(default=False)), ('avatar', wagtail.images.blocks.ImageChooserBlock()), ('feed', wagtail.core.blocks.StreamBlock([('feed', wagtail.core.blocks.StructBlock([('data', wagtail.core.blocks.StreamBlock([('commit', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('datetime', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True)), ('issue', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('datetime', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True)), ('pr', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('datetime', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True)), ('review', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('datetime', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=False, icon='fa-newspaper-o', null=True))], blank=True, null=True)), ('history', wagtail.core.blocks.StreamBlock([('history', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('datetime', wagtail.core.blocks.DateTimeBlock())], blank=False, icon='fa-newspaper-o', null=True))], blank=True, null=True)), ('languages', wagtail.core.blocks.StreamBlock([('language', wagtail.core.blocks.StructBlock([('language_name', wagtail.core.blocks.CharBlock()), ('color', esite.colorfield.blocks.ColorBlock()), ('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], icon='cogs', null=True))], blank=True, null=True)),
                ('project_tab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('projects_section', wagtail.core.fields.StreamField([('S_ProjectBlock', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Project name', null=True, required=True)), ('url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', null=True, required=True)), ('description', wagtail.core.blocks.TextBlock(help_text='Project description', null=True, required=False)), ('maintainer_name', wagtail.core.blocks.CharBlock()), ('maintainer_username', wagtail.core.blocks.CharBlock()), ('maintainer_email', wagtail.core.blocks.EmailBlock()), ('contributors', wagtail.core.blocks.StreamBlock([('contributor', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('username', wagtail.core.blocks.CharBlock()), ('active', wagtail.core.blocks.BooleanBlock(default=False)), ('avatar', wagtail.images.blocks.ImageChooserBlock()), ('feed', wagtail.core.blocks.StreamBlock([('feed', wagtail.core.blocks.StructBlock([('data', wagtail.core.blocks.StreamBlock([('commit', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('datetime', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True)), ('issue', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('datetime', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True)), ('pr', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('datetime', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True)), ('review', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('datetime', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=False, icon='fa-newspaper-o', null=True))], blank=True, null=True)), ('history', wagtail.core.blocks.StreamBlock([('history', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('datetime', wagtail.core.blocks.DateTimeBlock())], blank=False, icon='fa-newspaper-o', null=True))], blank=True, null=True)), ('languages', wagtail.core.blocks.StreamBlock([('language', wagtail.core.blocks.StructBlock([('language_name', wagtail.core.blocks.CharBlock()), ('color', esite.colorfield.blocks.ColorBlock()), ('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=False, icon='fa-user', null=True))])), ('test', wagtail.core.blocks.ChooserBlock(target_model=esite.ops.ops_scpages.models.ContributionFeed)), ('history', wagtail.core.blocks.StreamBlock([('history', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('datetime', wagtail.core.blocks.DateTimeBlock())], blank=False, icon='fa-newspaper-o', null=True))], blank=True, null=True)), ('languages', wagtail.core.blocks.StreamBlock([('language', wagtail.core.blocks.StructBlock([('language_name', wagtail.core.blocks.CharBlock()), ('color', esite.colorfield.blocks.ColorBlock()), ('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], icon='cogs', null=True))], blank=True, null=True)),
                ('imprint_tab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('telefax', models.CharField(blank=True, max_length=255, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_contactline', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=255, null=True)),
                ('court_of_registry', models.CharField(blank=True, max_length=255, null=True)),
                ('place_of_registry', models.CharField(blank=True, max_length=255, null=True)),
                ('trade_register_number', models.CharField(blank=True, max_length=255, null=True)),
                ('ownership', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('employee_count', models.CharField(blank=True, max_length=255, null=True)),
                ('opensource_url', models.URLField(blank=True, null=True)),
                ('recruiting_url', models.URLField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('settings_tab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cache', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='bigintegerfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='booleanfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='charfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='datefield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='datetimefield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='decimalfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='durationfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='emailfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='floatfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='genericipaddressfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='imagefield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='integerfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='nullbooleanfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='positiveintegerfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='positivesmallintegerfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='slugfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='smallintegerfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='textfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='timefield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='urlfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='uuidfield',
        ),
        migrations.CreateModel(
            name='ContributionFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, null=True)),
                ('datetime', models.DateTimeField(max_length=255, null=True)),
                ('message', models.CharField(max_length=255, null=True)),
                ('files', modelcluster.fields.ParentalManyToManyField(related_name='files', to='ops_scpages.ContributionFile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
