# Generated by Django 2.2.12 on 2020-08-08 01:37

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ops_scpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeLanguageStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=255, null=True)),
                ('insertions', models.IntegerField(null=True)),
                ('deletions', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeTransitionStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insertions', models.IntegerField(null=True)),
                ('deletions', models.IntegerField(null=True)),
                ('datetime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('avatar', models.ImageField(upload_to='')),
                ('codelanguages', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='contributor_codelanguages', to='ops_scpages.CodeTransitionStatistic')),
                ('codetransition', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='contributor_codetransition', to='ops_scpages.CodeTransitionStatistic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='opsscpagepage',
            name='feed',
        ),
        migrations.AddField(
            model_name='contributionfeed',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epfeed', to='ops_scpages.OpsScpagePage'),
        ),
        migrations.AddField(
            model_name='contributionfile',
            name='feed',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epfeed2', to='ops_scpages.OpsScpagePage'),
        ),
        migrations.AlterField(
            model_name='contributionfeed',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contributionfeed',
            name='files',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, null=True, related_name='files', to='ops_scpages.ContributionFile'),
        ),
        migrations.AlterField(
            model_name='contributionfile',
            name='deletions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contributionfile',
            name='insertions',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('url', models.URLField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('owner_name', models.URLField(max_length=255, null=True)),
                ('owner_username', models.URLField(max_length=255, null=True)),
                ('maintainer_email', models.EmailField(max_length=254, null=True)),
                ('codelanguages', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='project_codelanguages', to='ops_scpages.CodeTransitionStatistic')),
                ('codetransition', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='project_codetransition', to='ops_scpages.CodeTransitionStatistic')),
                ('contributors', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='project_contributor', to='ops_scpages.Contributor')),
                ('feed', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='project_feed', to='ops_scpages.ContributionFeed')),
                ('page', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opsprojects', to='ops_scpages.OpsScpagePage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contributor',
            name='feed',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='contributor_feed', to='ops_scpages.ContributionFeed'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epcontributor', to='ops_scpages.OpsScpagePage'),
        ),
    ]
