# Generated by Django 2.2.12 on 2020-08-02 23:07

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('ops_scpages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='bigintegerfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='booleanfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='charfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='datefield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='datetimefield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='decimalfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='durationfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='emailfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='floatfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='genericipaddressfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='imagefield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='integerfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='nullbooleanfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='positiveintegerfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='positivesmallintegerfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='slugfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='smallintegerfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='textfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='timefield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='urlfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='uuidfield',
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='projects_section',
            field=wagtail.core.fields.StreamField([('S_ProjectBlock', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Project name', null=True, required=True)), ('url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', null=True, required=True)), ('description', wagtail.core.blocks.TextBlock(help_text='Project description', null=True, required=False)), ('maintainer', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('username', wagtail.core.blocks.CharBlock()), ('active', wagtail.core.blocks.BooleanBlock(default=False)), ('avatar', wagtail.images.blocks.ImageChooserBlock()), ('feed', wagtail.core.blocks.StreamBlock([('feed', wagtail.core.blocks.StructBlock([('datetime', wagtail.core.blocks.DateTimeBlock(null=True, required=True)), ('action', wagtail.core.blocks.CharBlock(help_text='Type of feed', null=True, required=True)), ('data', wagtail.core.blocks.StreamBlock([('commit', wagtail.core.blocks.StructBlock([('commit', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=False, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-user', null=True, required=False)), ('contributions', wagtail.core.blocks.StreamBlock([('users', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('username', wagtail.core.blocks.CharBlock()), ('active', wagtail.core.blocks.BooleanBlock(default=False)), ('avatar', wagtail.images.blocks.ImageChooserBlock()), ('feed', wagtail.core.blocks.StreamBlock([('feed', wagtail.core.blocks.StructBlock([('datetime', wagtail.core.blocks.DateTimeBlock(null=True, required=True)), ('action', wagtail.core.blocks.CharBlock(help_text='Type of feed', null=True, required=True)), ('data', wagtail.core.blocks.StreamBlock([('commit', wagtail.core.blocks.StructBlock([('commit', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=False, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=False, icon='fa-user', null=True))]))], icon='cogs', null=True))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='users_section',
            field=wagtail.core.fields.StreamField([('S_UserBlock', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('username', wagtail.core.blocks.CharBlock()), ('active', wagtail.core.blocks.BooleanBlock(default=False)), ('avatar', wagtail.images.blocks.ImageChooserBlock()), ('feed', wagtail.core.blocks.StreamBlock([('feed', wagtail.core.blocks.StructBlock([('datetime', wagtail.core.blocks.DateTimeBlock(null=True, required=True)), ('action', wagtail.core.blocks.CharBlock(help_text='Type of feed', null=True, required=True)), ('data', wagtail.core.blocks.StreamBlock([('commit', wagtail.core.blocks.StructBlock([('commit', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=False, icon='fa-newspaper-o', null=True))], blank=True, null=True))], icon='cogs', null=True))], blank=True, null=True),
        ),
    ]
