# Generated by Django 2.2.12 on 2020-08-08 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops_scpages', '0003_auto_20200808_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributionfeed',
            name='page',
        ),
        migrations.RemoveField(
            model_name='project',
            name='page',
        ),
    ]
