# Generated by Django 2.2.12 on 2020-08-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_scpages', '0004_auto_20200803_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsscpagespage',
            name='cache',
            field=models.TextField(null=True),
        ),
    ]
