# Generated by Django 2.2.12 on 2020-08-08 02:04

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ops_scpages', '0004_auto_20200808_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opsprojects', to='ops_scpages.OpsScpagePage'),
        ),
    ]
