# Generated by Django 2.2.12 on 2020-08-08 02:49

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ops_scpages', '0005_project_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelanguagestatistic',
            name='color',
            field=models.CharField(default='Unkown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='codelanguagestatistic',
            name='deletions',
            field=models.IntegerField(default='Unkown', null=True),
        ),
        migrations.AlterField(
            model_name='codelanguagestatistic',
            name='insertions',
            field=models.IntegerField(default='Unkown', null=True),
        ),
        migrations.AlterField(
            model_name='codelanguagestatistic',
            name='name',
            field=models.CharField(default='Unkown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='codetransitionstatistic',
            name='deletions',
            field=models.IntegerField(default='Unkown', null=True),
        ),
        migrations.AlterField(
            model_name='codetransitionstatistic',
            name='insertions',
            field=models.IntegerField(default='Unkown', null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='codelanguages',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='contributor_codelanguages', to='ops_scpages.CodeLanguageStatistic'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='name',
            field=models.CharField(default='Unkown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='username',
            field=models.CharField(default='Unkown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='codelanguages',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='project_codelanguages', to='ops_scpages.CodeLanguageStatistic'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='Unkown', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='Unkown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner_email',
            field=models.EmailField(default='Unkown', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner_name',
            field=models.URLField(default='Unkown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner_username',
            field=models.URLField(default='Unkown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(default='Unkown', max_length=255, null=True),
        ),
    ]
