# Generated by Django 2.2.12 on 2020-08-08 11:39

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ops_scpages', '0006_auto_20200808_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='codetransition',
        ),
        migrations.AddField(
            model_name='codetransitionstatistic',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transition_project', to='ops_scpages.Project'),
        ),
    ]
