# Generated by Django 2.2.12 on 2020-08-08 11:55

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ops_scpages', '0007_auto_20200808_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codetransitionstatistic',
            name='page',
        ),
        migrations.AddField(
            model_name='contributionfeed',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epfeed', to='ops_scpages.OpsScpagePage'),
        ),
    ]
