# Generated by Django 2.2.12 on 2020-08-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_scpages', '0008_auto_20200808_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner_name',
            field=models.CharField(default='Unkown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner_username',
            field=models.CharField(default='Unkown', max_length=255, null=True),
        ),
    ]
