# Generated by Django 2.2.12 on 2020-08-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops_scpages', '0009_auto_20200808_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='feed',
        ),
    ]
