# Generated by Django 2.2.12 on 2020-08-08 13:23

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ops_scpages', '0010_remove_project_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feed',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='project_feed', to='ops_scpages.ContributionFeed'),
        ),
    ]
