# Generated by Django 2.2.12 on 2020-08-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_scpages', '0011_project_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='Unkown', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, default='Unkown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner_email',
            field=models.EmailField(blank=True, default='Unkown', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner_name',
            field=models.CharField(blank=True, default='Unkown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner_username',
            field=models.CharField(blank=True, default='Unkown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, default='Unkown', max_length=255, null=True),
        ),
    ]
