# Generated by Django 2.2.12 on 2020-08-09 15:45

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ops_scpages', '0012_auto_20200808_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='codetransition',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='project_codetransition', to='ops_scpages.CodeTransitionStatistic'),
        ),
    ]
