# Generated by Django 2.2.12 on 2020-08-03 00:54

from django.db import migrations
import esite.colorfield.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ops_scpages', '0014_auto_20200803_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='statistic',
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='history',
            field=wagtail.core.fields.StreamField([('history', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock())], blank=False, icon='fa-newspaper-o', null=True))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='languages',
            field=wagtail.core.fields.StreamField([('language', wagtail.core.blocks.StructBlock([('language_name', wagtail.core.blocks.CharBlock()), ('color', esite.colorfield.blocks.ColorBlock()), ('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True),
        ),
    ]
