# Generated by Django 2.2.12 on 2020-08-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops_scpages', '0015_auto_20200803_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='history',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='projects_section',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='users_section',
        ),
    ]
