# Generated by Django 2.2.12 on 2020-08-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_scpages', '0017_auto_20200803_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsscpagespage',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='court_of_registry',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='employee_count',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='opensource_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='ownership',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='place_of_registry',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='recruiting_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='tax_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='telefax',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='telephone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='trade_register_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='vat_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='whatsapp_contactline',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='whatsapp_telephone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='zip_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opsscpagespage',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
