# Generated by Django 2.2.12 on 2020-08-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_scpages', '0020_auto_20200803_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsscpagespage',
            name='imprint_tab_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='overview_tab_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='project_tab_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='settings_tab_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opsscpagespage',
            name='users_tab_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
