# Generated by Django 2.2.12 on 2020-08-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_scpages', '0022_auto_20200803_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsscpagespage',
            name='cache',
            field=models.TextField(blank=True, null=True),
        ),
    ]
