# Generated by Django 2.2.12 on 2020-08-03 21:17

from django.db import migrations, models
import django.db.models.deletion
import esite.colorfield.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('ops_scpages', '0023_auto_20200803_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsScpagePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('overview_tab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('feed_section', wagtail.core.fields.StreamField([('feed', wagtail.core.blocks.StructBlock([('datetime', wagtail.core.blocks.DateTimeBlock(null=True, required=True)), ('data', wagtail.core.blocks.StreamBlock([('commit', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True)), ('issue', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True)), ('pr', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True)), ('review', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=False, icon='fa-newspaper-o', null=True))], blank=True, null=True)),
                ('history_section', wagtail.core.fields.StreamField([('history', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock())], blank=False, icon='fa-newspaper-o', null=True))], blank=True, null=True)),
                ('languages_section', wagtail.core.fields.StreamField([('language', wagtail.core.blocks.StructBlock([('language_name', wagtail.core.blocks.CharBlock()), ('color', esite.colorfield.blocks.ColorBlock()), ('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True)),
                ('users_tab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('users_section', wagtail.core.fields.StreamField([('S_UserBlock', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('username', wagtail.core.blocks.CharBlock()), ('active', wagtail.core.blocks.BooleanBlock(default=False)), ('avatar', wagtail.images.blocks.ImageChooserBlock()), ('feed', wagtail.core.blocks.StreamBlock([('feed', wagtail.core.blocks.StructBlock([('datetime', wagtail.core.blocks.DateTimeBlock(null=True, required=True)), ('data', wagtail.core.blocks.StreamBlock([('commit', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True)), ('issue', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True)), ('pr', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True)), ('review', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=False, icon='fa-newspaper-o', null=True))], blank=True, null=True)), ('history', wagtail.core.blocks.StreamBlock([('history', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock())], blank=False, icon='fa-newspaper-o', null=True))], blank=True, null=True)), ('languages', wagtail.core.blocks.StreamBlock([('language', wagtail.core.blocks.StructBlock([('language_name', wagtail.core.blocks.CharBlock()), ('color', esite.colorfield.blocks.ColorBlock()), ('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], icon='cogs', null=True))], blank=True, null=True)),
                ('project_tab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('projects_section', wagtail.core.fields.StreamField([('S_ProjectBlock', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Project name', null=True, required=True)), ('url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', null=True, required=True)), ('description', wagtail.core.blocks.TextBlock(help_text='Project description', null=True, required=False)), ('maintainer_name', wagtail.core.blocks.CharBlock()), ('maintainer_username', wagtail.core.blocks.CharBlock()), ('maintainer_email', wagtail.core.blocks.EmailBlock()), ('contributors', wagtail.core.blocks.StreamBlock([('contributor', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('username', wagtail.core.blocks.CharBlock()), ('active', wagtail.core.blocks.BooleanBlock(default=False)), ('avatar', wagtail.images.blocks.ImageChooserBlock()), ('feed', wagtail.core.blocks.StreamBlock([('feed', wagtail.core.blocks.StructBlock([('datetime', wagtail.core.blocks.DateTimeBlock(null=True, required=True)), ('data', wagtail.core.blocks.StreamBlock([('commit', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True)), ('issue', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True)), ('pr', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True)), ('review', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=False, icon='fa-newspaper-o', null=True))], blank=True, null=True)), ('history', wagtail.core.blocks.StreamBlock([('history', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock())], blank=False, icon='fa-newspaper-o', null=True))], blank=True, null=True)), ('languages', wagtail.core.blocks.StreamBlock([('language', wagtail.core.blocks.StructBlock([('language_name', wagtail.core.blocks.CharBlock()), ('color', esite.colorfield.blocks.ColorBlock()), ('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=False, icon='fa-user', null=True))])), ('feed', wagtail.core.blocks.StreamBlock([('feed', wagtail.core.blocks.StructBlock([('datetime', wagtail.core.blocks.DateTimeBlock(null=True, required=True)), ('data', wagtail.core.blocks.StreamBlock([('commit', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True)), ('issue', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True)), ('pr', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True)), ('review', wagtail.core.blocks.StructBlock([('contribution_id', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.TextBlock()), ('files', wagtail.core.blocks.StreamBlock([('file', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('path', wagtail.core.blocks.CharBlock()), ('raw_changes', wagtail.core.blocks.TextBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], blank=False, icon='fa-newspaper-o', null=True))], blank=True, null=True)), ('history', wagtail.core.blocks.StreamBlock([('history', wagtail.core.blocks.StructBlock([('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock()), ('date', wagtail.core.blocks.DateTimeBlock())], blank=False, icon='fa-newspaper-o', null=True))], blank=True, null=True)), ('languages', wagtail.core.blocks.StreamBlock([('language', wagtail.core.blocks.StructBlock([('language_name', wagtail.core.blocks.CharBlock()), ('color', esite.colorfield.blocks.ColorBlock()), ('insertions', wagtail.core.blocks.CharBlock()), ('deletions', wagtail.core.blocks.CharBlock())], blank=True, icon='fa-newspaper-o', null=True))], blank=True, null=True))], icon='cogs', null=True))], blank=True, null=True)),
                ('imprint_tab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('telefax', models.CharField(blank=True, max_length=255, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_contactline', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=255, null=True)),
                ('court_of_registry', models.CharField(blank=True, max_length=255, null=True)),
                ('place_of_registry', models.CharField(blank=True, max_length=255, null=True)),
                ('trade_register_number', models.CharField(blank=True, max_length=255, null=True)),
                ('ownership', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('employee_count', models.CharField(blank=True, max_length=255, null=True)),
                ('opensource_url', models.URLField(blank=True, null=True)),
                ('recruiting_url', models.URLField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('settings_tab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cache', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='address',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='cache',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='city',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='court_of_registry',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='employee_count',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='feed_section',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='history_section',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='imprint_tab_name',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='languages_section',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='opensource_url',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='overview_tab_name',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='ownership',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='place_of_registry',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='project_tab_name',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='projects_section',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='recruiting_url',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='settings_tab_name',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='telefax',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='trade_register_number',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='users_section',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='users_tab_name',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='vat_number',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='whatsapp_contactline',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='whatsapp_telephone',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='zip_code',
        ),
    ]
