# Generated by Django 2.2.12 on 2020-08-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_dashboard', '0003_auto_20200801_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsdashbordpage',
            name='intro',
            field=models.CharField(max_length=255),
        ),
    ]
