# Generated by Django 2.2.12 on 2020-08-02 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops_dashboard', '0004_auto_20200801_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opsdashbordpage',
            name='intro',
        ),
    ]
