version: "3.1"

services:
  #> PostgreSQL
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=changeme
    restart: always

  #> Mongo
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=ops_analytics
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - 27017:27017

  #> Django
  app:
    build: .
    environment:
      - "DJANGO_SECRET_KEY=changeme"
      - "DATABASE_URL=postgres://app_user:changeme@db/app_db"
      - "DEFAULT_ENTERPRISE_NAME=snek"
      - "HIVE_PASSWORD=test"
    links:
      - "db:db"
    ports:
      - "8000:8000/tcp"
    depends_on:
      - "db"
# SPDX-License-Identifier: (EUPL-1.2)
# Copyright © 2019-2020 Simon Prast
