# Generated by Django 2.2.12 on 2020-08-16 16:31

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hive_enterprise", "0001_initial"),
        ("hive_connector", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="enterprise_page",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connector_scp_page",
                to="hive_enterprise.EnterpriseFormPage",
            ),
        ),
    ]
