# Generated by Django 2.2.12 on 2020-08-02 13:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('ops_pipelines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsPipelineFormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, verbose_name='to address')),
                ('from_address', models.CharField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('head', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='bigintegerfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='booleanfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='charfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='datefield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='datetimefield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='decimalfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='durationfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='emailfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='floatfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='genericipaddressfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='imagefield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='integerfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='nullbooleanfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='positiveintegerfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='positivesmallintegerfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='slugfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='smallintegerfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='textfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='timefield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='urlfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='uuidfield',
        ),
        migrations.AlterField(
            model_name='opspipelinespage',
            name='sections',
            field=wagtail.core.fields.StreamField([('S_PipelineBlock', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Name of the presentator', null=True, required=True)), ('url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', null=True, required=True)), ('description', wagtail.core.blocks.TextBlock(help_text='Other information', null=True, required=False)), ('activity_history', wagtail.core.blocks.StreamBlock([('activity', wagtail.core.blocks.StructBlock([('datetime', wagtail.core.blocks.DateTimeBlock(null=True, required=True))], blank=False, icon='fa-calendar-check-o', null=True))], blank=False, null=True)), ('verified', wagtail.core.blocks.BooleanBlock(default=False, help_text='Whether the attendee was attending or not', null=False, required=False)), ('token', wagtail.core.blocks.CharBlock())], icon='cogs', null=True))], null=True),
        ),
        migrations.CreateModel(
            name='OpsPipelineFormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.TextField()),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='submit time')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'form submission',
                'verbose_name_plural': 'form submissions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpsPipelineFormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.CharField(blank=True, help_text='Default value. Comma separated values supported for checkboxes.', max_length=255, verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='ops_pipelines.OpsPipelineFormPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
