# Generated by Django 2.2.12 on 2020-08-02 13:35

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pipelines', '0002_auto_20200802_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opspipelinespage',
            name='sections',
            field=wagtail.core.fields.StreamField([('S_PipelineBlock', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Name of the presentator', null=True, required=True)), ('url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', null=True, required=True)), ('description', wagtail.core.blocks.TextBlock(help_text='Other information', null=True, required=False)), ('activity_history', wagtail.core.blocks.StreamBlock([('activity', wagtail.core.blocks.StructBlock([('datetime', wagtail.core.blocks.DateTimeBlock(null=True, required=True))], blank=False, icon='fa-calendar-check-o', null=True))], blank=True, null=True)), ('verified', wagtail.core.blocks.BooleanBlock(default=False, help_text='Whether the attendee was attending or not', null=False, required=False)), ('token', wagtail.core.blocks.CharBlock())], icon='cogs', null=True))], null=True),
        ),
    ]
