# Generated by Django 2.2.12 on 2020-08-04 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pipelines', '0005_pipeline_pipeline_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='activity_history',
        ),
        migrations.AddField(
            model_name='pipeline_activity',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_name', to='ops_pipelines.Pipeline'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='token',
            field=models.CharField(blank=True, help_text='Warning! Changing the token affects the connection to all endpoints.', max_length=255, null=True),
        ),
    ]
