# Generated by Django 2.2.12 on 2020-08-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('ops_connectors', '0003_connectorformfield_connectorformpage_connectorformsubmission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('ops_pipelines', '0006_auto_20200804_1135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpsPipelinesPage',
        ),
    ]
