# Generated by Django 2.2.12 on 2020-08-04 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pipelines', '0007_delete_opspipelinespage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline_activity',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ops_pipelines.Pipeline'),
        ),
    ]
