# Generated by Django 2.2.12 on 2020-08-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pipelines', '0008_auto_20200804_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='url',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Pipeline_Activity',
        ),
    ]
