# Generated by Django 2.2.12 on 2020-08-04 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pipelines', '0009_auto_20200804_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='domain',
        ),
        migrations.CreateModel(
            name='PipelineActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(null=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops_pipelines.Pipeline')),
            ],
        ),
    ]
