# Generated by Django 2.2.12 on 2020-08-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops_scpages', '0024_auto_20200803_2317'),
        ('ops_pipelines', '0010_auto_20200804_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='company_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_scp_page', to='ops_scpages.OpsScpagePage'),
        ),
    ]
