# Generated by Django 2.2.12 on 2020-08-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pipelines', '0011_pipeline_company_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
