# Generated by Django 2.2.12 on 2020-08-03 17:46

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ops_scpages', '0022_auto_20200803_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gitlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('domain', models.CharField(max_length=255, null=True)),
                ('token', models.CharField(help_text='Warning! Changing the token affects the connection to all endpoints.', max_length=255, null=True)),
                ('privilegies_mode', models.CharField(choices=[('polp', 'Principle of least privilege'), ('idc', 'Open privilege')], default='isolate', max_length=255)),
                ('company_page', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gitlab_scp_page', to='ops_scpages.OpsScpagesPage')),
            ],
        ),
    ]
