# Generated by Django 2.2.12 on 2020-08-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gitlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(max_length=255, null=True)),
                ('token', models.CharField(help_text='Warning! Changing the token affects the connection to all endpoints.', max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('privilegies_mode', models.CharField(choices=[('polp', 'Principle of least privilege'), ('idc', 'Open privilege')], default='isolate', max_length=255)),
            ],
        ),
    ]
