# Generated by Django 2.2.12 on 2020-08-07 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops_scpages', '0002_auto_20200808_0105'),
        ('ops_gitlabs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlab',
            name='company_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gitlab_scp_page', to='ops_scpages.OpsScpagePage'),
        ),
    ]
