# Generated by Django 2.2.12 on 2020-08-04 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops_gitlabs', '0003_auto_20200804_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlab',
            name='company_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gitlab_scp_page', to='ops_scpages.OpsScpagePage'),
        ),
    ]
