# Generated by Django 2.2.12 on 2020-08-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_gitlabs', '0004_auto_20200804_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlab',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
