# Generated by Django 2.2.12 on 2020-08-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_connector', '0002_connector_enterprise_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='is_hashed',
            field=models.BooleanField(default=True),
        ),
    ]
