# Generated by Django 2.2.12 on 2020-08-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_connector', '0002_connector_enterprise_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='privileges_mode',
            field=models.CharField(choices=[('POLP', 'Principle of least privilege'), ('IDC', 'Open privilege')], default='POLP', max_length=255),
        ),
    ]
