# Generated by Django 2.2.12 on 2020-08-13 03:06

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("ops_connector", "0003_connector_is_hashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connector",
            name="enterprise_page",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connector_scp_page",
                to="ops_enterprise.EnterpriseFormPage",
            ),
        ),
    ]
