# Generated by Django 2.2.12 on 2020-08-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_initial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snekuser",
            name="is_enterprise",
            field=models.BooleanField(default=False, verbose_name="enterprise"),
        ),
    ]
