# Generated by Django 2.2.12 on 2020-08-10 10:21

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ops_enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codelanguagestatistic',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_language_statistic', to='ops_enterprise.EnterpriseFormPage'),
        ),
        migrations.AddField(
            model_name='codetransitionstatistic',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_transition_statistic', to='ops_enterprise.EnterpriseFormPage'),
        ),
        migrations.AlterField(
            model_name='contributionfeed',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_feed', to='ops_enterprise.EnterpriseFormPage'),
        ),
        migrations.AlterField(
            model_name='contributionfile',
            name='feed',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_contribution_feed', to='ops_enterprise.EnterpriseFormPage'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributor', to='ops_enterprise.EnterpriseFormPage'),
        ),
    ]
