# Generated by Django 2.2.12 on 2020-08-10 10:56

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ops_enterprise', '0002_auto_20200810_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='feed',
            new_name='contribution_feed',
        ),
        migrations.AlterField(
            model_name='project',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_projects', to='ops_enterprise.EnterpriseFormPage'),
        ),
    ]
