# Generated by Django 2.2.12 on 2020-08-07 18:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_auto_20200729_2232"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("registration", "0001_initial"),
        ("wagtailsearchpromotions", "0002_capitalizeverbose"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("wagtailforms", "0004_add_verbose_name_plural"),
        ("enterprise", "0003_auto_20200807_1419"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EnterpriseRootPage", new_name="EnterpriseIndex",
        ),
    ]
