# Generated by Django 2.2.12 on 2020-08-10 10:59

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ops_enterprise', '0003_auto_20200810_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionfeed',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_contribution_feed', to='ops_enterprise.EnterpriseFormPage'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_contributors', to='ops_enterprise.EnterpriseFormPage'),
        ),
    ]
