# Generated by Django 2.2.12 on 2020-08-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops_enterprise', '0004_auto_20200810_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='feed',
            new_name='contribution_feed',
        ),
    ]
