# Generated by Django 2.2.12 on 2020-08-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0005_enterpriseformsubmission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enterpriseformpage", options={"verbose_name": "Enterprise Form Page"},
        ),
        migrations.AlterModelOptions(
            name="enterpriseindex", options={"verbose_name": "Enterprise Index"},
        ),
    ]
