# Generated by Django 2.2.12 on 2020-08-10 11:10

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ops_enterprise', '0008_auto_20200810_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelanguagestatistic',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_codelanguage_statistic', to='ops_enterprise.EnterpriseFormPage'),
        ),
    ]
