# Generated by Django 2.2.12 on 2020-08-10 11:20

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ops_enterprise', '0009_auto_20200810_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionfile',
            name='feed',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_contribution_feed', to='ops_enterprise.ContributionFeed'),
        ),
    ]
