# Generated by Django 2.2.12 on 2020-08-10 11:43

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ops_enterprise', '0010_auto_20200810_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='codelanguages',
        ),
        migrations.AddField(
            model_name='contributor',
            name='codelanguages',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributor_codelanguages', to='ops_enterprise.CodeLanguageStatistic'),
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='codetransition',
        ),
        migrations.AddField(
            model_name='contributor',
            name='codetransition',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributor_codetransition', to='ops_enterprise.CodeTransitionStatistic'),
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='contribution_feed',
        ),
        migrations.AddField(
            model_name='contributor',
            name='contribution_feed',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributor_feed', to='ops_enterprise.ContributionFeed'),
        ),
    ]
