# Generated by Django 2.2.12 on 2020-08-10 11:48

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ops_enterprise', '0011_auto_20200810_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='codelanguages',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='codetransition',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='contribution_feed',
        ),
        migrations.AddField(
            model_name='contributor',
            name='project',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_contributor', to='ops_enterprise.EnterpriseFormPage'),
        ),
    ]
