# Generated by Django 2.2.12 on 2020-08-10 11:50

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ops_enterprise', '0012_auto_20200810_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='codelanguages',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='contributor_codelanguages', to='ops_enterprise.CodeLanguageStatistic'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='codetransition',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='contributor_codetransition', to='ops_enterprise.CodeTransitionStatistic'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='contribution_feed',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='contributor_feed', to='ops_enterprise.ContributionFeed'),
        ),
    ]
