# Generated by Django 2.2.12 on 2020-08-10 12:08

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ops_enterprise', '0013_auto_20200810_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='project',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_contributor', to='ops_enterprise.Project'),
        ),
    ]
