# Generated by Django 2.2.12 on 2020-09-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20200729_2232'),
        ('hive_enterprise', '0002_auto_20200816_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseformpage',
            name='avatar_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.SNEKImage'),
        ),
    ]
