# Generated by Django 2.2.12 on 2020-09-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive_pipeline', '0002_auto_20200921_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opspipelineformpage',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opspipelineformpage',
            name='head',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
